defaultSemverRangePrefix: ""

enableScripts: false

packageExtensions:
  "@ethereumjs/vm@*":
    dependencies:
      rlp: "^2.0.0"
  "@chakra-ui/button@*":
    dependencies:
      "@chakra-ui/react-utils": "^1.0.0"

yarnPath: .yarn/releases/yarn-3.1.0-rc.5.cjs
